### ISSUE TITLE
Password API semantics

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#12]
API endpoints that accept a `password_hash` from the client should be renamed to receive `password` since clients send the non-hashed password.

**Comment by thefueley** [comment]
This is fixed on `("/api/v1/user", h.CreateUser).Methods("POST")`
Need to fix on `("/api/v1/user/{id:[0-9]+}", JWTAuth(h.UpdateUserPassword)).Methods("PUT")`
