### ISSUE TITLE
Endpoint to create a user times out.

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#21]
Making a `POST` request to `https://test.seismos.io:3000/api/v1/user/` times out in Postman.

Body example:
```json
{
    "username": "sufhdsjkcndjksnvcdscdscjsdv",
    "password": "cds8coijdscndslcm4ipfkdscsdcs"
}
```

**Comment by thefueley** [comment]
Can you try: https://test.seismos.io/api/v1/user

Request: {"username": "user8", "password": "user8"}
Response: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MmRmMTYwLTlhMDAtNDU1NC05OWI1LTU5MTZmZDc5MjNmNiIsImlzc3VlciI6IlNjaG9sYXItUG93ZXIiLCJ1c2VybmFtZSI6InVzZXI4IiwiaXNzdWVkX2F0IjoiMjAyMy0wMS0zMVQxNzo1NDozNi40ODAyNDEyOVoiLCJleHBpcmVkX2F0IjoiMjAyMy0wMS0zMVQxODowNDozNi40ODAyNDEzOVoifQ.b8_ADa1MVthhLoZqsL_X5gMMTL8ti4jt83bLuqjBB3M"

**Comment by MoistCode** [comment]
`https://test.seismos.io/api/v1/user` works. Moving forward, are all v1 endpoints going to be on `https://test.seismos.io/api/v1/*` instead of `https://test.seismos.io:3000/api/v1/*`?

**Comment by thefueley** [comment]
@MoistCode, yes. That is right.
