### ISSUE TITLE
List of workouts endpoint request

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#33]
To avoid multiple backend (and perhaps even DB calls) from the frontend, we should establish endpoints that do a lot of the work for us.

**Method**: `GET`

**Endpoint**: whatever makes sense to backend resource practices

**Description**: Lists all workouts so we can show users a list of workouts they can start.

**Expected response data example**:
```json
[
  {
    "ID": "1", // Workout ID
    "Name": "Test Workout",
    "CreatedAt": "2023-02-06 19:30:55.000",
    "EditedAt": "2023-02-07 19:30:55.000",
    "CreatorID": "1", // User ID
  },
  {
    "ID": "2", // Workout ID
    "Name": "Test Workout 2",
    "CreatedAt": "2023-02-06 19:30:55.000",
    "EditedAt": "2023-02-07 19:30:55.000",
    "CreatorID": "1", // User ID
  },
  {
    "ID": "1", // Workout ID
    "Name": "Test Workout 3",
    "CreatedAt": "2023-02-06 19:30:55.000",
    "EditedAt": "2023-02-07 19:30:55.000",
    "CreatorID": "1", // User ID
  }
]
```

**Comment by thefueley** [comment]
Addressed in [pull/35](https://github.com/thefueley/scholar-power-api/pull/35)

**Comment by thefueley** [comment]
Endpoint: `https://test.seismos.io/api/v1/workout/user`
Body: `{"name": "user1"}`
`[
    {
        "PlanID": "1",
        "Name": "Ab Day",
        "CreatedAt": "2023-02-10 06:49:41.000",
        "EditedAt": "2023-02-10 06:49:41.000",
        "CreatorID": "1"
    }
]`

**Comment by thefueley** [comment]
Endpoint: `https://test.seismos.io/api/v1/workout/user`
Body: `{"name": "user2"}`
`[
    {
        "PlanID": "4",
        "Name": "Core",
        "CreatedAt": "2023-02-10 06:49:41.000",
        "EditedAt": "2023-02-10 06:49:41.000",
        "CreatorID": "2"
    }
]`

**Comment by MoistCode** [comment]
@thefueley Can we update this endpoint to not receive a body so maybe something like `/api/v1/workout/user/<USERNAME>`?

HTTP GETs do not generally have wide support for a body and isn't recommended and sometimes ignored. [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/fetch) is one of those web API's tha reject GETs with a body.

`Note that a request using the GET or HEAD method cannot have a body.`

**Comment by thefueley** [comment]
@MoistCode. Updated. Give it a try. Let me know if you run into any issues.
