### ISSUE TITLE
Authentication Errors Should Return 403

### ISSUE THREAD

**Issue by thefueley** [thefueley/scholar-power-api#43]
Backend returns 500 error for the following scenarios:

On Login:
entering a bad password
entering a user that doesn't exist

On Register:
entering a user that already exists

Fix the errors to be 403.

**Comment by thefueley** [comment]
Thanks for the update, @ZacharySI 

@MoistCode, can you verify this fix from the UI?

**Comment by MoistCode** [comment]
@thefueley Hey sorry about the delay. I tested empty sign up, sign up with an already existing user, and invalid login creds. They do not result in a 500.

**Comment by MoistCode** [comment]
On a side note, not sure if this differs from the rest on purpose. Empty signup result in a 400 instead of a 403.

**Comment by thefueley** [comment]
I think a "Bad Request" may be appropriate for an empty sign-up request. We can change it, if you want it to be something else.

**Comment by MoistCode** [comment]
Nah this is fine, I was just curious.
