### ISSUE TITLE
Local Development CORS

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#44]
Running both the frontend and backend locally does not currently allow for communication due to CORS.

We should set up the backend to allow for `OPTIONS` methods to pass through for preflight requests. A CORS specific middleware can check for this HTTP method and return the appropriate header(s). This is NOT an exact implementation but is instead a first pass since I've ran it and it seems to work for local development:

```go
func CORSMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "https://deft-torte-4578e5.netlify.app, http://localhost:8100/")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}
		next.ServeHTTP(w, r)
	})
}
```

This middleware should be added to our list of middlewares. Something else that should be done is to allow our routes to accept `OPTIONS` methods. The quick test fix I had was to add `"OPTIONS"` to every single route but that may not be the best approach so I'll defer to backend specialists to come up with a better implementation if there is one.

**Comment by thefueley** [comment]
A bit of background on the current architecture. There is an NGINX instance funneling traffic to the Docker instance that's running our API. 
<img width="308" alt="arch" src="https://user-images.githubusercontent.com/5083152/218355746-287ae1fb-0679-4843-ba1f-60752d017937.png">


For that reason, I have to set CORS settings in two places. The Go middleware has some minimal CORS settings. 
<img width="755" alt="go" src="https://user-images.githubusercontent.com/5083152/218355858-cc1688b0-6c5f-4942-aa4a-1ed34cb547e8.png">


Rather, I have set all these CORS settings in NGINX.
<img width="1053" alt="nginx" src="https://user-images.githubusercontent.com/5083152/218355881-11457588-5694-43d4-ad5d-fe43b1dd1869.png">


Adding the CORSMiddleware _settings_ you listed _should not_ be a problem. We can add them, test them, and make sure they don't break anything. I suspect that adding these settings may require some tweaking on the proxy as well. We'll see.

**Comment by MoistCode** [comment]
Might be worth it to only apply the middleware I provided if we're running in development mode since NGINX is handling it in production.

**Comment by thefueley** [comment]
@MoistCode,
Can you checkout [Branch thefueley/issue44](https://github.com/thefueley/scholar-power-api/tree/thefueley/issue44) and see if that fixes this for you?

**Comment by MoistCode** [comment]
@thefueley The logic seems to be correct for the middleware but there's just one more thing. The routes we have themselves do not allow for the method `OPTIONS` to go through so this middleware won't get hit for the preflight requests. I can dig into this a little bit more tonight if you haven't had the chance to.

**Comment by thefueley** [comment]
@MoistCode
I added mux CORSMethodMiddleware. 
Results below. Can you test and confirm?

```
✅ ❯❯❯ curl -iL  -X OPTIONS http://localhost:3000/api/v1/user/test1                                                                                                                                [ 13 Feb 2023 @12:43 ]
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: https://deft-torte-4578e5.netlify.app, http://localhost:8100/
Date: Mon, 13 Feb 2023 16:43:32 GMT
Content-Length: 0
```

**Comment by MoistCode** [comment]
This looks like it's getting there although there is one issue. Since you've changed the HTTP methods to `PUT` from `POST`, there seems to be some additional changes you may need to add.

In my initial testing, POSTing to `/api/v1/user` resulted in a `POST http://0.0.0.0:3000/api/v1/user 405 (Method Not Allowed)`.

Change it to PUT then ends up with a:

```
Access to fetch at 'http://0.0.0.0:3000/api/v1/user' from origin 'http://localhost:8100' has been blocked by CORS policy: Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
```

**Comment by MoistCode** [comment]
Awesome, looks like it works. Ship it!

**Comment by thefueley** [comment]
Perfect!
