### ISSUE TITLE
[Request] Endpoint to create a workout plan

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#52]
The frontend would like to send data all at once once the user has completed creation.

Maybe `POST /api/v1/workoutplan`?

The FE would send something like this (arbitrary values):

```json
{
  "username": "testinguser",
  "name": "My Workout Plan",
  "exercises": [
    {
      "sets": "5",
      "reps": "3",
      "load": "10 lbs",
      "exercise_id": "1",
      "instruction_id": "31"
    },
    {
      "sets": "3",
      "reps": "1",
      "load": "105 lbs",
      "exercise_id": "5",
      "instruction_id": "63"
    },
    {
      "sets": "10",
      "reps": "10",
      "load": "Bodyweight",
      "exercise_id": "32",
      "instruction_id": "1"
    },
    {
      "sets": "1",
      "reps": "50",
      "load": "Bodyweight",
      "exercise_id": "15",
      "instruction_id": "21"
    }
  ]
}
```

On a side note, I added `username` as a field to send. Some examples in the README has `creator_id` which I'm fine with sending as well. If we go the `creator_id` route, can we add the user's ID to the JWT token we send back to avoid an additional call to the backend to get the ID from the username in the JWT?

**Comment by thefueley** [comment]
Sample token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4OThmZjk1LWI2ZmUtNGYwYi04ODNkLTI4YjI1NGQ2YmYxMCIsInVpZCI6IjEiLCJpc3N1ZXIiOiJTY2hvbGFyLVBvd2VyIiwidXNlcm5hbWUiOiJ1c2VyMSIsImlzc3VlZF9hdCI6IjIwMjMtMDItMTZUMTI6MTE6NTIuNjY3ODQzLTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDItMTdUMTI6MTE6NTIuNjY3ODQzLTA1OjAwIn0.gvAFkiZe6iiab7wC6rLzaW9hie1I2oDzyIAnWxxGEjE`

Endpoint: POST `/api/v1/workout`
Required:
`uid`
`name`
`exercises{sets, reps, load, exercise_id}`

Sample create exercise: 
`{"uid": "1", "name": "Lower #1", "exercises": [ {"sets": "3", "reps": "8", "load": "135", "exercise_id": "89"}, {"sets": "3", "reps": "5", "load": "135", "exercise_id": "77"}]}`

Response: `{
    "Message": "workout created"
}`

New response from GET `/api/v1/workout/user/{username}`
`[
    {
        "PlanID": "1",
        "Name": "Ab Day",
        "CreatedAt": "2023-02-16 17:11:45.000",
        "EditedAt": "2023-02-16 17:11:45.000",
        "CreatorID": "1"
    },
    {
        "PlanID": "3",
        "Name": "Abs",
        "CreatedAt": "2023-02-16 17:11:45.000",
        "EditedAt": "2023-02-16 17:11:45.000",
        "CreatorID": "1"
    },
    {
        "PlanID": "23c8a47f-341a-4de6-b60e-ea3493b1b11e",
        "Name": "Lower #1",
        "CreatedAt": "2023-02-16 12:16:02.12164 -0500 EST m=+257.004440147",
        "EditedAt": "2023-02-16 12:16:02.12164 -0500 EST m=+257.004440147",
        "CreatorID": "1"
    }
]`

`creator_id` and `instruction_id` are no longer needed. `creator_id` is replaced with `uid` here. 

Will push this branch after verifying the rest of the package.

**Comment by thefueley** [comment]
All Workout endpoints are updated. 
Create  Workout
`POST /api/v1/workout`

Get User's Workout Plans
`GET /api/v1/workout/user/{username}`

Get Exercises in Workout Plan
`GET /api/v1/workout/{plan_id}`

Update Workout
`PUT /api/v1/workout/{plan_id}`

Delete Workout
`DELETE /api/v1/workout/{plan_id}`

**Comment by MoistCode** [comment]
Awesome. What's up with the oddly formatted date here on this item in one of your examples:

```json
  {
    "PlanID": "4af913d7-4d57-4ee5-9f93-55893c182673",
    "Name": "Lower #2",
    "CreatedAt": "2023-02-16 21:52:56.840216068 +0000 UTC m=+2047.354681884",
    "EditedAt": "2023-02-16 21:52:56.840216068 +0000 UTC m=+2047.354681884",
    "CreatorID": "1"
  }
```

**Comment by thefueley** [comment]
Thanks. Didn't notice that. Updated.

**Comment by thefueley** [comment]
@MoistCode,

Fix is in place.
