### ISSUE TITLE
[Request] Support `DELETE /api/v1/history/ID`

### ISSUE THREAD

**Issue by MoistCode** [thefueley/scholar-power-api#68]
It doesn't look like we currently support deleting a history at `/api/v1/history/<ID>`

**Comment by thefueley** [comment]
Updated the routes for workout history. 

Get workout history `/api/v1/history/{uid}`  
Update workout history `/api/v1/history/{id}`  
Body:  
```
{
    "athlete_id": "1",
    "notes": "so-so 😕"
}
```
Delete workout history `/api/v1/history/{id}`  
Body:  
```
{
    "athlete_id": "1"
}
```

Enforced previously unenforced authz. Updated workout history section of `README`
