### ISSUE TITLE
User Model Should Return uid When CreateUser Exits

### ISSUE THREAD

**Issue by thefueley** [thefueley/scholar-power-api#9]
When a new user is created, the uid is missing in the response.
{
    "ID": "",
    "UserName": "user2",
    "PasswordHash": "$2a$10$NCGh.okQzKFuKadGdX0deOqtN2HVd.zvR1lRMZO5HeYvMMmtTSiQG"
}

**Comment by ZacharySI** [comment]
would something like: newuser.ID, _ = insertRow.LastInsertID() work in the CreateUser function? I'm still getting this running locally

**Comment by thefueley** [comment]
My thoughts are to add a line to createUserRow for ID, similar to UserName and PasswordHash. Then remove the newuser struct. Your return should be userRowToUser(createUserRow). Mind creating a fix branch and trying that out? We may have to change up the ExecContext SQL. We'll see.

**Comment by ZacharySI** [comment]
I'll do what I can, but expect me to break something

**Comment by thefueley** [comment]
I think this is fixed now, @ZacharySI. The new PR simply returns a token, rather than the json-struct above. We should be able to close this once y'all verify that [token-gen #13](https://github.com/thefueley/scholar-power-api/pull/13) works as expected.

**Comment by thefueley** [comment]
Closing as the issue is now extraneous. Returning the user token instead has made this irrelevant.
